# Generated by Django 4.2.6 on 2023-11-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
    ]
