# Generated by Django 4.2.6 on 2023-12-15 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_subscription_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='cost_amount',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 14, 18, 47, 30, 255261, tzinfo=datetime.timezone.utc)),
        ),
    ]
