# Generated by Django 4.2.6 on 2023-12-15 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_subscription_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='available_options',
            field=models.CharField(choices=[('view_unlimited', 'View All Movies Without Limitations'), ('quality_480', 'Quality 480p'), ('quality_720', 'Quality 720p'), ('quality_4k', 'Quality 4K'), ('recommendation_offers', 'Recommendation Offers')], default='view_unlimited', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 14, 19, 0, 43, 23147, tzinfo=datetime.timezone.utc)),
        ),
    ]
