# Generated by Django 4.2.6 on 2023-12-15 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_alter_movie_year_alter_subscription_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 14, 22, 49, 45, 470210, tzinfo=datetime.timezone.utc)),
        ),
    ]
