# Generated by Django 4.2.6 on 2023-12-15 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_alter_subscription_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 14, 23, 20, 26, 287600, tzinfo=datetime.timezone.utc)),
        ),
    ]
