# Generated by Django 4.2.6 on 2023-12-16 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0014_movie_description_alter_subscription_expiration_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Приобретенная Подписка', 'verbose_name_plural': 'Приобретенные Подписки'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionoption',
            options={'verbose_name': 'Доступная опция', 'verbose_name_plural': 'Доступные опции'},
        ),
        migrations.AlterModelOptions(
            name='subscriptiontype',
            options={'verbose_name': 'Тип Подписки', 'verbose_name_plural': 'Типы Подписок'},
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 15, 9, 43, 26, 897836, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='available_options',
            field=models.ManyToManyField(to='films.subscriptionoption', verbose_name='Доступные опции'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='cost_value',
            field=models.IntegerField(default=0, verbose_name='стоимость'),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='type_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название'),
        ),
    ]
