# Generated by Django 4.2.6 on 2023-12-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_alter_subscription_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
    ]
