# Generated by Django 4.2.6 on 2023-12-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_remove_subscription_expiration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Введите описание', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления записи')),
                ('is_active', models.BooleanField(default=True, help_text='Активный статус')),
                ('count', models.IntegerField(help_text='Количество чего-то')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена товара', max_digits=10)),
                ('image', models.ImageField(help_text='Изображение товара', upload_to='images/')),
                ('file', models.FileField(help_text='Файл', upload_to='files/')),
            ],
        ),
    ]
