# Generated by Django 4.2.6 on 2023-12-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0019_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='status_2',
            field=models.BooleanField(default=False),
        ),
    ]
